### PR TITLE
made it so user can input mongouri connection string and easily connect :)

### PR DESCRIPTION
**Pull request by superboxes**
Please test this as I didnt, i just hope dis works, atleast a kinda good idea tbh

### CODE REVIEW

**Comment by adambrangenberg** [comment]
Why though

**Comment by superboxes** [comment]
> Why thought

cuz yk, its in wok and many people switching from wok might miss it, still a nice little feature to have. In fact, I remember migzchi asking how to connect to mongodb using sdhandler, im just trying to contribute and add stuff.

Hello discord

**Comment by adambrangenberg** [comment]
But WOK has features that require it like setting a guild specific prefix

**Comment by superboxes** [comment]
> But WOK has features that require it like setting a guild specific prefix

well, damn, at least it saves like <5 lines of code then, im just tryna to contribute, its up to Agent anyways.

Hi discord

**Comment by adambrangenberg** [comment]
It feels like bloat to me ¯\_(ツ)_/¯

**Pull request closed without merging**
